
owner: syedarshad1 # Replace with your GitHub username
repo: url-monitoring        # The name of your repository

sites:
  - name: FIS API Health
    url: https://api-gw1-prod1.fisglobal.com/gw/v1/health
    method: GET
    expectStatus: 200
    maxResponseTime: 5000

status-website:
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /url-monitoring
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our GitHub repository. No server required — just GitHub Actions, Issues, and Pages. **Get your own for free**
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
